<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NewsSeeder extends Seeder
{
    public function run(): void
    {
        $news = [
            [
                'title' => 'Bupati Halmahera Utara Buka FGD Percepatan Akses Keuangan Daerah, Bappeda Dukung Implementasi IKAD',
                'slug' => 'bupati-halmahera-utara-buka-fgd-percepatan-akses-keuangan-daerah-bappeda-dukung-implementasi-ikad',
                'category' => 'Ekonomi & Keuangan',
                'image' => '/images/bappeda/fgd-keuangan.png',
                'date' => '2026-09-02',
                'views' => 542,
                'author' => 'Tim Humas BAPPEDA',
                'summary' => 'Bupati Halmahera Utara didampingi Kepala Bappeda membuka secara resmi Forum Group Discussion percepatan inklusi dan literasi keuangan daerah berbasis digital.',
                'content' => '<p>BAPEDA HALUT — Bupati Halmahera Utara secara resmi membuka Forum Group Discussion (FGD) Percepatan Akses Keuangan Daerah yang diselenggarakan bersama Bappeda Halmahera Utara untuk mempercepat implementasi IKAD di seluruh kecamatan.</p><p>Kepala Bappeda menyatakan dukungan penuh terhadap seluruh program percepatan inklusi keuangan guna menopang pembangunan ekonomi inklusif daerah dan pemberdayaan pelaku UMKM.</p>',
                'is_published' => true,
                'published_at' => '2026-09-02 09:00:00',
                'created_at' => '2026-09-02 09:00:00',
                'updated_at' => '2026-09-02 09:00:00',
            ],
            [
                'title' => 'Bappeda Halut Matangkan Sinkronisasi Rancangan Awal RPJMD 2025–2029 Selaras Target Nasional',
                'slug' => 'bappeda-halut-matangkan-sinkronisasi-rancangan-awal-rpjmd-2025-2029-selaras-target-nasional',
                'category' => 'Berita Utama',
                'image' => '/images/bappeda/rpjpn-rpjpd.jpg',
                'date' => '2026-08-28',
                'views' => 819,
                'author' => 'Bidang Perencanaan BAPPEDA',
                'summary' => 'Penyusunan RPJMD periode 2025–2029 memasuki babak pendalaman indikator makro ekonomi, penurunan kemiskinan ekstrem, dan penguatan konektivitas antarwilayah.',
                'content' => '<p>TOBELO — Bappeda Kabupaten Halmahera Utara menggelar forum sinkronisasi dokumen rancangan awal Rencana Pembangunan Jangka Menengah Daerah (RPJMD) 2025–2029 yang dihadiri oleh seluruh pimpinan perangkat daerah.</p><p>Fokus utama mencakup keselarasan arah kebijakan dengan RPJPN dan RPJPD Provinsi Maluku Utara, mencakup transformasi ekonomi biru, pengentasan kantong kemiskinan, serta peningkatan indeks modal manusia.</p>',
                'is_published' => true,
                'published_at' => '2026-08-28 10:00:00',
                'created_at' => '2026-08-28 10:00:00',
                'updated_at' => '2026-08-28 10:00:00',
            ],
            [
                'title' => 'Monitoring Progres Fisik Jembatan Garuda Kao Barat: Akselerasi Konektivitas Sentra Produksi',
                'slug' => 'monitoring-progres-fisik-jembatan-garuda-kao-barat-akselerasi-konektivitas-sentra-produksi',
                'category' => 'Infrastruktur',
                'image' => '/images/bappeda/jembatan-garuda.png',
                'date' => '2026-08-19',
                'views' => 637,
                'author' => 'Bidang Infrastruktur & Kewilayahan',
                'summary' => 'Peninjauan lapangan berkala memastikan jembatan penghubung lintas kecamatan rampung sesuai jadwal dan standar kelayakan teknis.',
                'content' => '<p>KAO BARAT — Tim Pengendalian dan Evaluasi Pembangunan Bappeda Halmahera Utara melakukan monitoring langsung ke lokasi pembangunan Jembatan Garuda di Kecamatan Kao Barat.</p><p>Infrastruktur strategis ini menghubungkan sentra pertanian dan perkebunan rakyat dengan jalur logistik utama menuju pelabuhan Tobelo, memangkas waktu tempuh distribusi hasil bumi warga.</p>',
                'is_published' => true,
                'published_at' => '2026-08-19 14:15:00',
                'created_at' => '2026-08-19 14:15:00',
                'updated_at' => '2026-08-19 14:15:00',
            ],
            [
                'title' => 'Penguatan Satu Data Indonesia (SDI) Halut: Bappeda Integrasikan Geoportal Web GIS & Statistik Sektoral',
                'slug' => 'penguatan-satu-data-indonesia-sdi-halut-bappeda-integrasikan-geoportal-web-gis-dan-statistik-sektoral',
                'category' => 'SPBE & Digital',
                'image' => '/images/bappeda/satu-data.jpg',
                'date' => '2026-08-10',
                'views' => 925,
                'author' => 'Bidang Litbang & SPBE',
                'summary' => 'Penerapan sistem portal data spasial terpadu memungkinkan analisis spasial real-time, transparansi anggaran proyek, dan akurasi perumusan kebijakan.',
                'content' => '<p>TOBELO — Sebagai koordinator Satu Data Indonesia tingkat kabupaten, Bappeda Halmahera Utara merilis integrasi geoportal berbasis Esri ArcGIS Engine dan database spasial terpadu.</p><p>Portal ini memungkinkan perangkat daerah dan publik mengakses peta delineasi batas wilayah, zonasi RTRW, serta sebaran lokasi proyek strategis secara presisi dan terbuka.</p>',
                'is_published' => true,
                'published_at' => '2026-08-10 11:30:00',
                'created_at' => '2026-08-10 11:30:00',
                'updated_at' => '2026-08-10 11:30:00',
            ],
            [
                'title' => 'Rakor Konvergensi Stunting 2026: Sinergi Lintas Sektor Bappeda Halut Capai Target Intervensi Spesifik',
                'slug' => 'rakor-konvergensi-stunting-2026-sinergi-lintas-sektor-bappeda-halut-capai-target-intervensi-spesifik',
                'category' => 'Sosial Budaya',
                'image' => '/images/bappeda/stunting-data.jpg',
                'date' => '2026-07-31',
                'views' => 482,
                'author' => 'Pokja Penurunan Stunting BAPPEDA',
                'summary' => 'Pelaksanaan rembuk stunting dan pemetaan desa lokus intervensi gizi terpadu guna mempercepat penurunan prevalensi stunting di 17 kecamatan.',
                'content' => '<p>TOBELO — Rapat Koordinasi Konvergensi Penurunan Stunting 2026 dipimpin oleh Kepala Bappeda selaku Ketua Tim Koordinasi Penanggulangan Kemiskinan dan Stunting Kabupaten Halmahera Utara.</p><p>Forum ini mengonsolidasikan 8 aksi konvergensi lintas dinas kesehatan, dinas pendidikan, serta pemerintah desa untuk memastikan intervensi gizi tepat sasaran.</p>',
                'is_published' => true,
                'published_at' => '2026-07-31 09:30:00',
                'created_at' => '2026-07-31 09:30:00',
                'updated_at' => '2026-07-31 09:30:00',
            ],
            [
                'title' => 'Penilaian Kinerja PPD 2026: Halmahera Utara Masuk Nominasi Perencanaan Pembangunan Daerah Terbaik',
                'slug' => 'penilaian-kinerja-ppd-2026-halmahera-utara-masuk-nominasi-perencanaan-pembangunan-daerah-terbaik',
                'category' => 'Inovasi Daerah',
                'image' => '/images/bappeda/penilaian-ppd.jpg',
                'date' => '2026-07-25',
                'views' => 1150,
                'author' => 'Tim BAPPEDA Halut',
                'summary' => 'Inovasi perencanaan partisipatif dan integrasi dashboard berbasis spasial membawa Halmahera Utara meraih apresiasi tinggi tim penilai nasional.',
                'content' => '<p>JAKARTA — Kabupaten Halmahera Utara berhasil menembus tahap verifikasi lanjutan Penghargaan Pembangunan Daerah (PPD) 2026 yang diselenggarakan Kementerian PPN/Bappenas.</p><p>Keberhasilan ini didorong oleh kualitas penyusunan RKPD yang komprehensif, capaian target makro yang konsisten, dan terobosan digitalisasi layanan Satu Data Halut.</p>',
                'is_published' => true,
                'published_at' => '2026-07-25 08:45:00',
                'created_at' => '2026-07-25 08:45:00',
                'updated_at' => '2026-07-25 08:45:00',
            ],
            [
                'title' => 'Kepala Bappeda Halmahera Utara Jadi Narasumber pada Konferensi Pendidikan Indonesia 2026 di Sleman',
                'slug' => 'kepala-bappeda-halmahera-utara-jadi-narasumber-pada-konferensi-pendidikan-indonesia-2026-di-sleman',
                'category' => 'Berita Utama',
                'image' => '/images/bappeda/kepala-bappeda.png',
                'date' => '2026-07-02',
                'views' => 740,
                'author' => 'Tim Humas BAPPEDA',
                'summary' => 'Pemaparan strategi inovasi alokasi dana transfer daerah untuk afirmasi sekolah rakyat dan penguatan kapasitas tenaga pendidik wilayah kepulauan.',
                'content' => '<p>SLEMAN — Kepala Bappeda Kabupaten Halmahera Utara menghadiri Konferensi Pendidikan Indonesia 2026 sebagai narasumber utama memaparkan strategi inovasi alokasi dana pendidikan daerah dan akselerasi SDM berkualitas di kawasan timur Indonesia.</p><p>Paparan ini menekankan pentingnya intervensi sarana teknologi informasi pada sekolah di daerah 3T agar kesenjangan mutu pembelajaran dapat ditekan.</p>',
                'is_published' => true,
                'published_at' => '2026-07-02 10:30:00',
                'created_at' => '2026-07-02 10:30:00',
                'updated_at' => '2026-07-02 10:30:00',
            ],
            [
                'title' => 'Pokja PKP Halut Bahas Rencana Kawasan Permukiman Kumuh & Sanitasi Layak Berkelanjutan',
                'slug' => 'pokja-pkp-halut-bahas-rencana-kawasan-permukiman-kumuh-dan-sanitasi-layak-berkelanjutan',
                'category' => 'Pembangunan',
                'image' => '/images/bappeda/pokja-pkp.jpg',
                'date' => '2026-06-25',
                'views' => 395,
                'author' => 'Pokja PKP BAPPEDA',
                'summary' => 'Penyelarasan rencana aksi penanganan kawasan perumahan dan permukiman kumuh terintegrasi dengan penyediaan akses air minum aman.',
                'content' => '<p>TOBELO — Kelompok Kerja Perumahan dan Kawasan Permukiman (Pokja PKP) Bappeda Halmahera Utara menggelar lokakarya penajaman program penataan lingkungan permukiman.</p><p>Rencana penataan berfokus pada kawasan pesisir Tobelo dan Galela dengan mengedepankan sanitasi ramah lingkungan dan proteksi sempadan pantai.</p>',
                'is_published' => true,
                'published_at' => '2026-06-25 13:00:00',
                'created_at' => '2026-06-25 13:00:00',
                'updated_at' => '2026-06-25 13:00:00',
            ],
            [
                'title' => 'Rapat Evaluasi Penyelenggaraan Statistik Sektoral (EPSS): Bappeda Mantapkan Rekomendasi BPS',
                'slug' => 'rapat-evaluasi-penyelenggaraan-statistik-sektoral-epss-bappeda-mantapkan-rekomendasi-bps',
                'category' => 'SPBE & Digital',
                'image' => '/images/bappeda/evaluasi-epss.jpg',
                'date' => '2026-06-18',
                'views' => 510,
                'author' => 'Bidang Litbang & Statistik',
                'summary' => 'Optimalisasi Indeks Pembangunan Statistik (IPS) Halmahera Utara menuju predikat baik melalui standardisasi metadata dan interoperabilitas sistem.',
                'content' => '<p>TOBELO — Evaluasi Penyelenggaraan Statistik Sektoral (EPSS) dilaksanakan bersama BPS Halmahera Utara guna mereview kepatuhan produsen data di lingkup Pemkab Halut.</p><p>Hasil evaluasi menjadi dasar penyempurnaan katalog data statistik daerah dalam portal Satu Data Bappeda Halut.</p>',
                'is_published' => true,
                'published_at' => '2026-06-18 09:15:00',
                'created_at' => '2026-06-18 09:15:00',
                'updated_at' => '2026-06-18 09:15:00',
            ],
            [
                'title' => 'Rapat Kerja BAPPEDA Halmahera Utara 2026: Penguatan Disiplin Kerja & Efektivitas Pengawalan RKPD',
                'slug' => 'rapat-kerja-bappeda-halmahera-utara-2026-penguatan-disiplin-kerja-dan-efektivitas-pengawalan-rkpd',
                'category' => 'Pembangunan',
                'image' => '/images/bappeda/raker-2024.jpg',
                'date' => '2026-06-05',
                'views' => 670,
                'author' => 'Sekretariat BAPPEDA',
                'summary' => 'Konsolidasi internal seluruh bidang untuk mempertajam target kinerja triwulanan dan responsivitas layanan perencanaan bagi OPD.',
                'content' => '<p>TOBELO — Rapat Kerja Bappeda Kabupaten Halmahera Utara tahun 2026 berlangsung khidmat dengan penandatanganan pakta integritas kinerja seluruh pejabat administrator dan pengawas.</p><p>Raker menegaskan komitmen Bappeda sebagai \'dapur\' pemikiran pembangunan daerah yang profesional, akuntabel, dan solutif bagi kemaslahatan masyarakat Halut.</p>',
                'is_published' => true,
                'published_at' => '2026-06-05 08:30:00',
                'created_at' => '2026-06-05 08:30:00',
                'updated_at' => '2026-06-05 08:30:00',
            ],
        ];

        foreach ($news as $n) {
            DB::table('news')->updateOrInsert(
                ['slug' => $n['slug']],
                $n
            );
        }
    }
}
